name: Test

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  ActionTest:
    runs-on: ubuntu-latest
    steps:
      - name: Action-Test
        uses: PSModule/GitHub-Script@event
        with:
          Prerelease: true